insert into tb_alumnos values(1,'SEYDI YARIZA ALVARADO CORDERO',10,12,13,16,'A');
insert into tb_alumnos values(2,'FRANCISCO ALEJANDRO BAIL�N L�MUS',8,2,15,22,'B');
insert into tb_alumnos values(3,'GUADALUPE DIANA RUB� BARAHONA CASIA',5,6,40,6,'C');
insert into tb_alumnos values(4,'JESUS ANTONIO CALDERAS LEMUS',6,19,30,10,'D');
insert into tb_alumnos values(5,'WAGNER CASTA�EDA LINARES',5,17,20,1,'A');
insert into tb_alumnos values(6,'EDWAR ALEJANDRO CASTELLANOS PORTILLO',2,4,16,29,'B');
insert into tb_alumnos values(7,'JENNIFER YAHILINE CHAVEZ BOLA�OS',10,14,28,6,'C');
insert into tb_alumnos values(8,'SARA MAR�A CHINCHILLA CHINCHILLA',9,8,9,29,'D');
insert into tb_alumnos values(9,'IRIS MAGALY DAMIAN RODR�GUEZ',7,13,34,6,'A');
insert into tb_alumnos values(10,'LEIDY AMABLIAI ESQUIVEL LINARES',6,5,5,30,'B');
insert into tb_alumnos values(11,'GLORIA STEFANNIE FLANDEZ MARROQU�N',1,3,4,27,'C');
insert into tb_alumnos values(12,'LUIS FERNANDO GARCIA LUCERO',10,18,40,24,'D');
insert into tb_alumnos values(13,'JONATHAN JOSUE HERN�NDEZ ALVARADO',7,3,7,5,'A');
insert into tb_alumnos values(14,'LESTER ANTONIO LEMUS LUCERO',9,15,7,14,'B');
insert into tb_alumnos values(15,'JORGE ALFONSO L�PEZ GARC�A',3,10,40,16,'C');
insert into tb_alumnos values(16,'CRISTIAN EL� LUNA ARRIAGA',7,1,38,7,'D');
insert into tb_alumnos values(17,'JEFFERSON ALEXIS MOLINA SANABRIA',9,8,1,18,'A');
insert into tb_alumnos values(18,'BRANDON JOSU� MONTESFLORES RECINOS',4,9,17,14,'B');
insert into tb_alumnos values(19,'GREDYS ELISEO MORALES ORTIZ',2,1,5,5,'C');
insert into tb_alumnos values(20,'MARJORIE ALEXANDRA MORAN N�JERA',3,20,12,19,'D');
insert into tb_alumnos values(21,'MAR�A ALEJANDRA OCA�A PALACIOS',8,11,19,9,'A');
insert into tb_alumnos values(22,'RUBEN ANTONIO PEDROZA RECINOS',6,4,28,1,'B');
insert into tb_alumnos values(23,'MARIAN DULCEMARIA PORTILLO L�MUS',8,7,2,14,'C');
insert into tb_alumnos values(24,'STIVEN OSWALDO RAMOS HERN�NDEZ',9,6,16,24,'D');
insert into tb_alumnos values(25,'EMANUEL ISAAC ROQUE SANDOVAL',8,1,27,30,'A');
insert into tb_alumnos values(26,'BYRON ADOLFO SALGUERO ESTRADA',4,6,21,23,'B');
insert into tb_alumnos values(27,'LUISA DANIELA SCHLENKER ENRIQUEZ',5,4,6,23,'C');
insert into tb_alumnos values(28,'FERNANDO JOS� V�SQUEZ GONZ�LEZ',10,19,30,7,'D');
insert into tb_alumnos values(29,'VICTOR MANUEL V�SQUEZ GONZ�LEZ',9,17,38,8,'A');
insert into tb_alumnos values(30,'OSMAN JOSU� YES URQUILLA',3,17,6,13,'B');
insert into tb_alumnos values(31,'YANCARLOS EMANUEL ARANA NAJARRO',1,14,16,8,'C');
insert into tb_alumnos values(32,'WALVER OMAR ARANA NAJARRO',6,14,2,28,'D');
insert into tb_alumnos values(33,'JES�S ANTONIO BARRERA MOR�N',3,9,22,22,'A');
insert into tb_alumnos values(34,'HENRY DANIEL BARRIENTOS FLORES',4,2,34,2,'B');
insert into tb_alumnos values(35,'MARCO ALEXANDER CARRILLO GONZ�LEZ',7,6,21,2,'C');
insert into tb_alumnos values(36,'GREDYS ENRIQUE CARRILLO P�REZ',10,10,33,27,'D');
insert into tb_alumnos values(37,'LINDA DANIELA CASTILLO GIR�N',5,20,39,23,'A');
insert into tb_alumnos values(38,'DARLIN AMANDA CISNEROS REVOLORIO',8,2,19,4,'B');
insert into tb_alumnos values(39,'NERY CONTRERAS TOBAR',7,15,31,8,'C');
insert into tb_alumnos values(40,'MABELYN BERENISE CRUZ JIMENEZ',9,12,23,11,'D');
insert into tb_alumnos values(41,'PETER JOEL DUQUE POLANCO',5,8,31,10,'A');
insert into tb_alumnos values(42,'ANNER RONALDO ESCOBAR CR�Z',10,4,25,14,'B');
insert into tb_alumnos values(43,'STEVEN REN� GARC�A PAY�S',3,7,21,13,'C');
insert into tb_alumnos values(44,'ASHLEY MARINA GONZ�LEZ GONZ�LEZ',9,10,1,10,'D');
insert into tb_alumnos values(45,'DIEGO DANIEL GONZALEZ L�PEZ',10,20,15,25,'A');
insert into tb_alumnos values(46,'JOSU� ALBERTO GUEVARA L�PEZ',4,12,27,20,'B');
insert into tb_alumnos values(47,'ANTHONY ROMEO HERN�NDEZ DE LA CRUZ',4,11,33,9,'C');
insert into tb_alumnos values(48,'JORGE ANTONIO HERN�NDEZ N�JERA',4,16,36,20,'D');
insert into tb_alumnos values(49,'NERY JOS� MART�NEZ BOLA�OS',9,18,20,18,'A');
insert into tb_alumnos values(50,'DULCE MAR�A MAZARIEGOS MORALES',10,13,35,22,'B');
insert into tb_alumnos values(51,'SERGIO ARMANDO EMANUEL MENDEZ ALDANA',3,14,32,4,'C');
insert into tb_alumnos values(52,'CARLOS ARNOLDO M�NDEZ MEJ�A',4,19,32,17,'D');
insert into tb_alumnos values(53,'MARCOS JOSUE PEREZ AREVALO',5,8,34,27,'A');
insert into tb_alumnos values(54,'CARLOS FERNANDO PINEDA RIVERA',5,4,9,28,'B');
insert into tb_alumnos values(55,'BRYAN JOS� QUINTEROS P�REZ',10,4,33,29,'C');
insert into tb_alumnos values(56,'BRAYAM RAM�REZ ARANA',3,15,16,4,'D');
insert into tb_alumnos values(57,'LUIS OSWALDO RECINOS SOTO',5,16,30,24,'A');
insert into tb_alumnos values(58,'KEVIN GEOVANY RIVERA GUEVARA',9,2,36,15,'B');
insert into tb_alumnos values(59,'MAR�A CELESTE SOSA RECINOS',8,4,12,10,'C');
insert into tb_alumnos values(60,'DARWIN ADOLFO SOTO PALMA',9,18,34,30,'D');
